### ISSUE TITLE
 An error occurred while running semantic-release: { Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by OvidiuBan** [semantic-release/git#91]
Greetings!  What could be the problem?

### Current behavior
On the prepare step, the git plugin commits with fails

### Expected behavior
The git plugin should pass during the build.

### Environment
semantic-release version: v15.10.6
semantic-release/git: v7.0.5

![image](https://user-images.githubusercontent.com/11694812/47807437-b6409300-dd44-11e8-967d-51d08b3d338e.png)

**Comment by pvdlg** [comment]
Can you provide the logs with the full stacktrace? And a link to your repo? And your semantic-release configuration?

**Comment by pvdlg** [comment]
For information the problem is that at least one of the file the plugin is trying to commit is too long to be handled by Node. There is no much we can do here.
It's likely that you generate a file with a very long name and included it in the `assets` glob by mistake. But I can tell for sure without the information requested above.

**Comment by OvidiuBan** [comment]
Here is the stacktrace for the semantic-release.

2018-11-01T08:30:32.4551740Z ##[section]Starting: Yarn semantic-release
2018-11-01T08:30:32.4571734Z ==============================================================================
2018-11-01T08:30:32.4571734Z Task         : Yarn task
2018-11-01T08:30:32.4571734Z Description  : Executes Yarn
2018-11-01T08:30:32.4571734Z Version      : 2.6.999
2018-11-01T08:30:32.4571734Z Author       : Geek Learning
2018-11-01T08:30:32.4571734Z Help         : [More Information](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Yarn) (Version 2.6.999).
 
Dear Angular and Ember CLI users, please check our [known issues](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Known-Issues)
2018-11-01T08:30:32.4571734Z ==============================================================================
2018-11-01T08:30:33.7291964Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\Agents\TFS2013-1\_work\_tool\yarn\1.12.1\x64\yarn-v1.12.1\bin\yarn.cmd semantic-release"
2018-11-01T08:30:34.4902130Z yarn run v1.12.1
2018-11-01T08:30:34.6882146Z warning package.json: No license field
2018-11-01T08:30:34.7742168Z $ semantic-release
2018-11-01T08:30:38.1702829Z [09:30:38] [semantic-release] » i  Running semantic-release version 15.10.6
2018-11-01T08:30:43.0353764Z [09:30:43] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/changelog" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T08:30:43.0353764Z [09:30:43] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/npm" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T08:30:43.1603769Z [09:30:43] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/git" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T08:30:43.1613813Z [09:30:43] [semantic-release] » √  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2018-11-01T08:30:43.1623798Z [09:30:43] [semantic-release] » √  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2018-11-01T08:30:43.1663800Z [09:30:43] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/changelog" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T08:30:43.1703805Z [09:30:43] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/git" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T08:30:43.1733807Z [09:30:43] [semantic-release] » √  Loaded plugin "publish" from "@semantic-release/npm" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T08:30:43.2183810Z [09:30:43] [semantic-release] » √  Run automated release from branch master
2018-11-01T08:30:47.7524663Z [09:30:47] [semantic-release] » √  Allowed to push to the Git repository
2018-11-01T08:30:47.7564671Z [09:30:47] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/changelog"
2018-11-01T08:30:47.7725568Z [09:30:47] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
2018-11-01T08:30:47.7725568Z [09:30:47] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/npm"
2018-11-01T08:30:47.8794655Z [09:30:47] [semantic-release] [@semantic-release/npm] » i  Verify authentication for registry https://www.myget.org/F/webfactory-public/npm/
2018-11-01T08:30:47.9034693Z [09:30:47] [semantic-release] [@semantic-release/npm] » i  Wrote NPM_TOKEN to C:\Agents\TFS2013-1\_work\87\s\.npmrc
2018-11-01T08:30:47.9384707Z [09:30:47] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/npm"
2018-11-01T08:30:47.9404696Z [09:30:47] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/git"
2018-11-01T08:30:47.9534678Z [09:30:47] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/git"
2018-11-01T08:30:55.8196182Z [09:30:55] [semantic-release] » i  Found git tag v1.44.1 associated with version 1.44.1
2018-11-01T08:30:56.1486554Z [09:30:56] [semantic-release] » i  Found 7 commits since last release
2018-11-01T08:30:56.1486554Z [09:30:56] [semantic-release] » i  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
2018-11-01T08:30:56.1696738Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: feat(Period Formatter Service): Fix tests failing
2018-11-01T08:30:56.1716732Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is minor
2018-11-01T08:30:56.1716732Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: build(Period Formatter): Remove import of common web infrastructure in attempt to fix the semantic-r
2018-11-01T08:30:56.1726255Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T08:30:56.1726255Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: feat(Package.Json): Add repository details
2018-11-01T08:30:56.1736252Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is minor
2018-11-01T08:30:56.1736252Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: feat(Period Formatter Service): Fix period formatter service
2018-11-01T08:30:56.1736252Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is minor
2018-11-01T08:30:56.1736252Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: build: Fix failing build due to string format
2018-11-01T08:30:56.1746243Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T08:30:56.1746243Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: build: Fix build failing
2018-11-01T08:30:56.1756244Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T08:30:56.1756244Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: fix(Add-Object-Dialog): Fix object id validation
2018-11-01T08:30:56.1756244Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is patch
2018-11-01T08:30:56.1756244Z [09:30:56] [semantic-release] [@semantic-release/commit-analyzer] » i  Analysis of 7 commits complete: minor release
2018-11-01T08:30:56.1766244Z [09:30:56] [semantic-release] » √  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
2018-11-01T08:30:56.2556299Z [09:30:56] [semantic-release] » i  The next release version is 1.45.0
2018-11-01T08:30:56.2576287Z [09:30:56] [semantic-release] » i  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2018-11-01T08:30:56.4556318Z [09:30:56] [semantic-release] » √  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2018-11-01T08:30:56.4556318Z [09:30:56] [semantic-release] » i  Start step "prepare" of plugin "@semantic-release/changelog"
2018-11-01T08:30:56.4826329Z [09:30:56] [semantic-release] [@semantic-release/changelog] » i  Update C:\Agents\TFS2013-1\_work\87\s\CHANGELOG.md
2018-11-01T08:30:56.4836342Z [09:30:56] [semantic-release] » √  Completed step "prepare" of plugin "@semantic-release/changelog"
2018-11-01T08:30:56.5586351Z [09:30:56] [semantic-release] » i  Start step "prepare" of plugin "@semantic-release/git"
2018-11-01T08:30:56.9056376Z [09:30:56] [semantic-release] » ×  Failed step "prepare" of plugin "@semantic-release/git"
2018-11-01T08:30:56.9116387Z [09:30:56] [semantic-release] » ×  An error occurred while running semantic-release: { Error: spawn ENAMETOOLONG
2018-11-01T08:30:56.9116387Z     at _errnoException (util.js:1022:11)
2018-11-01T08:30:56.9116387Z     at ChildProcess.spawn (internal/child_process.js:323:11)
2018-11-01T08:30:56.9116387Z     at Object.exports.spawn (child_process.js:502:9)
2018-11-01T08:30:56.9116387Z     at Module.module.exports (C:\Agents\TFS2013-1\_work\87\s\node_modules\execa\index.js:205:26)
2018-11-01T08:30:56.9126410Z     at Function.module.exports.stdout.args [as stdout] (C:\Agents\TFS2013-1\_work\87\s\node_modules\execa\index.js:319:45)
2018-11-01T08:30:56.9126410Z     at filterModifiedFiles (C:\Agents\TFS2013-1\_work\87\s\node_modules\@semantic-release\git\lib\git.js:13:23)
2018-11-01T08:30:56.9126410Z     at module.exports (C:\Agents\TFS2013-1\_work\87\s\node_modules\@semantic-release\git\lib\prepare.js:34:33)
2018-11-01T08:30:56.9126410Z     at <anonymous>
2018-11-01T08:30:56.9126410Z     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-11-01T08:30:56.9126410Z   code: 'ENAMETOOLONG',
2018-11-01T08:30:56.9126410Z   errno: 'ENAMETOOLONG',
2018-11-01T08:30:56.9126410Z   syscall: 'spawn',
2018-11-01T08:30:56.9126410Z   pluginName: '@semantic-release/git' }
2018-11-01T08:30:56.9136406Z { Error: spawn ENAMETOOLONG
2018-11-01T08:30:56.9136406Z     at _errnoException (util.js:1022:11)
2018-11-01T08:30:56.9136406Z     at ChildProcess.spawn (internal/child_process.js:323:11)
2018-11-01T08:30:56.9136406Z     at Object.exports.spawn (child_process.js:502:9)
2018-11-01T08:30:56.9136406Z     at Module.module.exports (C:\Agents\TFS2013-1\_work\87\s\node_modules\execa\index.js:205:26)
2018-11-01T08:30:56.9136406Z     at Function.module.exports.stdout.args [as stdout] (C:\Agents\TFS2013-1\_work\87\s\node_modules\execa\index.js:319:45)
2018-11-01T08:30:56.9136406Z     at filterModifiedFiles (C:\Agents\TFS2013-1\_work\87\s\node_modules\@semantic-release\git\lib\git.js:13:23)
2018-11-01T08:30:56.9136406Z     at module.exports (C:\Agents\TFS2013-1\_work\87\s\node_modules\@semantic-release\git\lib\prepare.js:34:33)
2018-11-01T08:30:56.9136406Z     at <anonymous>
2018-11-01T08:30:56.9136406Z     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-11-01T08:30:56.9136406Z   code: �[32m'ENAMETOOLONG'�[39m,
2018-11-01T08:30:56.9136406Z   errno: �[32m'ENAMETOOLONG'�[39m,
2018-11-01T08:30:56.9136406Z   syscall: �[32m'spawn'�[39m,
2018-11-01T08:30:56.9416401Z   pluginName: �[32m'@semantic-release/git'�[39m }error Command failed with exit code 1.
2018-11-01T08:30:56.9416401Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2018-11-01T08:30:56.9746430Z ##[error]Error: C:\Agents\TFS2013-1\_work\_tool\yarn\1.12.1\x64\yarn-v1.12.1\bin\yarn.cmd failed with return code: 1
2018-11-01T08:30:56.9906423Z ##[section]Finishing: Yarn semantic-release








Here is the config for the semantic release.
"config": {
        "commitizen": {
            "path": "cz-conventional-changelog"
        }
    },
    "release": {
        "prepare": [
            "@semantic-release/changelog",
            {
                "path": "@semantic-release/git",
                "assets": [
                    "CHANGELOG.md"
                ],
                "message": "chore(release): v${nextRelease.version} \n\n${nextRelease.notes}\n\n[***NO_CI***]"
            }
        ],
        "verifyConditions": [
            "@semantic-release/changelog",
            "@semantic-release/npm",
            "@semantic-release/git"
        ],
        "publish": [
            "@semantic-release/npm"
        ],
        "success": [],
        "fail": []
    },
    "dependencies": {
        "@semantic-release/changelog": "^3.0.0",
        "@semantic-release/git": "^7.0.3",
        "commitizen": "^2.10.1",
        "cpx": "^1.5.0",
        "cz-conventional-changelog": "^2.1.0",
        "semantic-release": "^15.9.12"
    }

**Comment by pvdlg** [comment]
Somehow it seems a lot of files, or files with very long names are globbed. and when passed to `filterModifiedFiles` Node fails. That's weird because you mentioned that the `asset` option is set to `['CHANGELOG.md']`.

Can you run semantic-release with the --debug option and provide the logs? That should show what files are actually resolved via glob.

**Comment by OvidiuBan** [comment]
2018-11-01T16:39:08.4967176Z ##[section]Starting: Yarn semantic-release --debug
2018-11-01T16:39:08.4967176Z ==============================================================================
2018-11-01T16:39:08.4967176Z Task         : Yarn task
2018-11-01T16:39:08.4967176Z Description  : Executes Yarn
2018-11-01T16:39:08.4967176Z Version      : 2.6.999
2018-11-01T16:39:08.4967176Z Author       : Geek Learning
2018-11-01T16:39:08.4967176Z Help         : [More Information](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Yarn) (Version 2.6.999).

Dear Angular and Ember CLI users, please check our [known issues](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Known-Issues)
2018-11-01T16:39:08.4967176Z ==============================================================================
2018-11-01T16:39:09.8248588Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\Agents\TFS2013-1\_work\_tool\yarn\1.12.1\x64\yarn-v1.12.1\bin\yarn.cmd semantic-release --debug"
2018-11-01T16:39:10.5920103Z yarn run v1.12.1
2018-11-01T16:39:10.6530124Z warning package.json: No license field
2018-11-01T16:39:10.8561396Z $ semantic-release --debug
2018-11-01T16:39:13.6991107Z [17:39:13] [semantic-release] » i  Running semantic-release version 15.10.6
2018-11-01T16:39:13.9490334Z 2018-11-01T16:39:13.948Z semantic-release:config options values: { branch: 'master',
2018-11-01T16:39:13.9490334Z   repositoryUrl: 'http://tfs2013:8080/tfs/DWH/WEBfactory.BACnet/_git/bacnet-web-controls',
2018-11-01T16:39:13.9490334Z   tagFormat: 'v${version}',
2018-11-01T16:39:13.9490334Z   plugins: 
2018-11-01T16:39:13.9490334Z    [ '@semantic-release/commit-analyzer',
2018-11-01T16:39:13.9490334Z      '@semantic-release/release-notes-generator',
2018-11-01T16:39:13.9490334Z      '@semantic-release/npm',
2018-11-01T16:39:13.9490334Z      '@semantic-release/github' ],
2018-11-01T16:39:13.9490334Z   prepare: 
2018-11-01T16:39:13.9490334Z    [ '@semantic-release/changelog',
2018-11-01T16:39:13.9490334Z      { path: '@semantic-release/git',
2018-11-01T16:39:13.9490334Z        assets: [Array],
2018-11-01T16:39:13.9490334Z        message: 'chore(release): v${nextRelease.version} \n\n${nextRelease.notes}\n\n[***NO_CI***]' } ],
2018-11-01T16:39:13.9490334Z   verifyConditions: 
2018-11-01T16:39:13.9490334Z    [ '@semantic-release/changelog',
2018-11-01T16:39:13.9490334Z      '@semantic-release/npm',
2018-11-01T16:39:13.9490334Z      '@semantic-release/git' ],
2018-11-01T16:39:13.9490334Z   publish: [ '@semantic-release/npm' ],
2018-11-01T16:39:13.9490334Z   success: [],
2018-11-01T16:39:13.9490334Z   fail: [],
2018-11-01T16:39:13.9490334Z   _: [],
2018-11-01T16:39:13.9490334Z   debug: true,
2018-11-01T16:39:13.9490334Z   '$0': 'node_modules\\semantic-release\\bin\\semantic-release.js' }
2018-11-01T16:39:17.6365781Z [17:39:17] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/changelog" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T16:39:17.6365781Z [17:39:17] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/npm" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T16:39:17.7303977Z [17:39:17] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/git" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T16:39:17.7303977Z [17:39:17] [semantic-release] » √  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2018-11-01T16:39:17.7303977Z [17:39:17] [semantic-release] » √  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2018-11-01T16:39:17.7459575Z [17:39:17] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/changelog" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T16:39:17.7459575Z [17:39:17] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/git" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T16:39:17.7459575Z [17:39:17] [semantic-release] » √  Loaded plugin "publish" from "@semantic-release/npm" in shareable config "@webfactory-public/semantic-release-config"
2018-11-01T16:39:17.7929316Z [17:39:17] [semantic-release] » √  Run automated release from branch master
2018-11-01T16:39:22.4491399Z [17:39:22] [semantic-release] » √  Allowed to push to the Git repository
2018-11-01T16:39:22.4491399Z [17:39:22] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/changelog"
2018-11-01T16:39:22.4647634Z [17:39:22] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
2018-11-01T16:39:22.4647634Z [17:39:22] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/npm"
2018-11-01T16:39:22.5585131Z [17:39:22] [semantic-release] [@semantic-release/npm] » i  Verify authentication for registry https://www.myget.org/F/webfactory-public/npm/
2018-11-01T16:39:22.5742008Z [17:39:22] [semantic-release] [@semantic-release/npm] » i  Wrote NPM_TOKEN to C:\Agents\TFS2013-1\_work\87\s\.npmrc
2018-11-01T16:39:22.5897643Z [17:39:22] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/npm"
2018-11-01T16:39:22.5897643Z [17:39:22] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/git"
2018-11-01T16:39:22.6054806Z [17:39:22] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/git"
2018-11-01T16:39:23.6679053Z 2018-11-01T16:39:23.651Z semantic-release:get-last-release found tags: [ { gitTag: 'v1.44.1', version: '1.44.1' }, { gitTag: 'v1.44.0', version: '1.44.0' }, { gitTag: 'v1.43.0', version: '1.43.0' }, { gitTag: 'v1.42.1', version: '1.42.1' }, { gitTag: 'v1.42.0', version: '1.42.0' }, { gitTag: 'v1.41.13', version: '1.41.13' }, { gitTag: 'v1.41.12', version: '1.41.12' }, { gitTag: 'v1.41.11', version: '1.41.11' }, { gitTag: 'v1.41.10', version: '1.41.10' }, { gitTag: 'v1.41.9', version: '1.41.9' }, { gitTag: 'v1.41.8', version: '1.41.8' }, { gitTag: 'v1.41.7', version: '1.41.7' }, { gitTag: 'v1.41.6', version: '1.41.6' }, { gitTag: 'v1.41.5', version: '1.41.5' }, { gitTag: 'v1.41.4', version: '1.41.4' }, { gitTag: 'v1.41.3', version: '1.41.3' }, { gitTag: 'v1.41.2', version: '1.41.2' }, { gitTag: 'v1.41.1', version: '1.41.1' }, { gitTag: 'v1.41.0', version: '1.41.0' }, { gitTag: 'v1.40.0', version: '1.40.0' }, { gitTag: 'v1.39.0', version: '1.39.0' }, { gitTag: 'v1.38.0', version: '1.38.0' }, { gitTag: 'v1.37.0', version: '1.37.0' }, { gitTag: 'v1.36.0', version: '1.36.0' }, { gitTag: 'v1.35.5', version: '1.35.5' }, { gitTag: 'v1.35.4', version: '1.35.4' }, { gitTag: 'v1.35.3', version: '1.35.3' }, { gitTag: 'v1.35.2', version: '1.35.2' }, { gitTag: 'v1.35.1', version: '1.35.1' }, { gitTag: 'v1.35.0', version: '1.35.0' }, { gitTag: 'v1.34.0', version: '1.34.0' }, { gitTag: 'v1.33.1', version: '1.33.1' }, { gitTag: 'v1.33.0', version: '1.33.0' }, { gitTag: 'v1.32.2', version: '1.32.2' }, { gitTag: 'v1.32.1', version: '1.32.1' }, { gitTag: 'v1.32.0', version: '1.32.0' }, { gitTag: 'v1.31.4', version: '1.31.4' }, { gitTag: 'v1.31.3', version: '1.31.3' }, { gitTag: 'v1.31.2', version: '1.31.2' }, { gitTag: 'v1.31.1', version: '1.31.1' }, { gitTag: 'v1.31.0', version: '1.31.0' }, { gitTag: 'v1.30.1', version: '1.30.1' }, { gitTag: 'v1.30.0', version: '1.30.0' }, { gitTag: 'v1.29.0', version: '1.29.0' }, { gitTag: 'v1.28.0', version: '1.28.0' }, { gitTag: 'v1.27.1', version: '1.27.1' }, { gitTag: 'v1.27.0', version: '1.27.0' }, { gitTag: 'v1.26.2', version: '1.26.2' }, { gitTag: 'v1.26.1', version: '1.26.1' }, { gitTag: 'v1.26.0', version: '1.26.0' }, { gitTag: 'v1.25.0', version: '1.25.0' }, { gitTag: 'v1.24.1', version: '1.24.1' }, { gitTag: 'v1.24.0', version: '1.24.0' }, { gitTag: 'v1.23.11', version: '1.23.11' }, { gitTag: 'v1.23.10', version: '1.23.10' }, { gitTag: 'v1.23.9', version: '1.23.9' }, { gitTag: 'v1.23.8', version: '1.23.8' }, { gitTag: 'v1.23.7', version: '1.23.7' }, { gitTag: 'v1.23.6', version: '1.23.6' }, { gitTag: 'v1.23.5', version: '1.23.5' }, { gitTag: 'v1.23.4', version: '1.23.4' }, { gitTag: 'v1.23.3', version: '1.23.3' }, { gitTag: 'v1.23.2', version: '1.23.2' }, { gitTag: 'v1.23.1', version: '1.23.1' }, { gitTag: 'v1.23.0', version: '1.23.0' }, { gitTag: 'v1.22.1', version: '1.22.1' }, { gitTag: 'v1.22.0', version: '1.22.0' }, { gitTag: 'v1.21.0', version: '1.21.0' }, { gitTag: 'v1.20.2', version: '1.20.2' }, { gitTag: 'v1.20.1', version: '1.20.1' }, { gitTag: 'v1.20.0', version: '1.20.0' }, { gitTag: 'v1.19.1', version: '1.19.1' }, { gitTag: 'v1.19.0', version: '1.19.0' }, { gitTag: 'v1.18.0', version: '1.18.0' }, { gitTag: 'v1.17.2', version: '1.17.2' }, { gitTag: 'v1.17.1', version: '1.17.1' }, { gitTag: 'v1.17.0', version: '1.17.0' }, { gitTag: 'v1.16.2', version: '1.16.2' }, { gitTag: 'v1.16.1', version: '1.16.1' }, { gitTag: 'v1.16.0', version: '1.16.0' }, { gitTag: 'v1.15.8', version: '1.15.8' }, { gitTag: 'v1.15.7', version: '1.15.7' }, { gitTag: 'v1.15.6', version: '1.15.6' }, { gitTag: 'v1.15.5', version: '1.15.5' }, { gitTag: 'v1.15.4', version: '1.15.4' }, { gitTag: 'v1.15.3', version: '1.15.3' }, { gitTag: 'v1.15.2', version: '1.15.2' }, { gitTag: 'v1.15.1', version: '1.15.1' }, { gitTag: 'v1.15.0', version: '1.15.0' }, { gitTag: 'v1.14.2', version: '1.14.2' }, { gitTag: 'v1.14.1', version: '1.14.1' }, { gitTag: 'v1.14.0', version: '1.14.0' }, { gitTag: 'v1.13.0', version: '1.13.0' }, { gitTag: 'v1.12.14', version: '1.12.14' }, { gitTag: 'v1.12.13', version: '1.12.13' }, { gitTag: 'v1.12.12', version: '1.12.12' }, { gitTag: 'v1.12.11', version: '1.12.11' }, { gitTag: 'v1.12.10', version: '1.12.10' }, { gitTag: 'v1.12.9', version: '1.12.9' }, { gitTag: 'v1.12.8', version: '1.12.8' }, ... 37 more items ]
2018-11-01T16:39:28.8085928Z [17:39:28] [semantic-release] » i  Found git tag v1.44.1 associated with version 1.44.1
2018-11-01T16:39:28.9179685Z 2018-11-01T16:39:28.901Z semantic-release:get-commits Use gitHead: 7797681a4e0df3e9d53b35d1f66ecd4f81681fe8
2018-11-01T16:39:28.9805222Z [17:39:28] [semantic-release] » i  Found 15 commits since last release
2018-11-01T16:39:28.9960952Z 2018-11-01T16:39:28.994Z semantic-release:get-commits Parsed commits: [ { commit: { long: '21483108b4cc26f6dc54dfee92b73a5b9e557a93', short: '2148310' }, tree: { long: '05846ff7236786b28c6fe2c21db8197bd11874a1', short: '05846ff' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T16:08:16.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T16:08:16.000Z }, subject: 'chore(workspace.xml): Remove workspace.xml', body: '', hash: '21483108b4cc26f6dc54dfee92b73a5b9e557a93', message: 'chore(workspace.xml): Remove workspace.xml', gitTags: '(HEAD, origin/master)', committerDate: 2018-11-01T16:08:16.000Z }, { commit: { long: '23b67b1b11c45cf4c39694b25c5f80a56f357560', short: '23b67b1' }, tree: { long: 'fe4e71e2e640496ca1eb964fffdcecefdc6d9931', short: 'fe4e71e' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T16:07:24.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T16:07:24.000Z }, subject: 'chore(Package.json): Update ko-am charts package', body: '', hash: '23b67b1b11c45cf4c39694b25c5f80a56f357560', message: 'chore(Package.json): Update ko-am charts package', gitTags: '', committerDate: 2018-11-01T16:07:24.000Z }, { commit: { long: 'addec4fff7520c20cb1ed8366caffc30e1aeb210', short: 'addec4f' }, tree: { long: '9023d519f6cc8e999a4102ac78ee655a751fffd3', short: '9023d51' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T13:39:50.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T13:39:50.000Z }, subject: 'Reset master branch', body: '', hash: 'addec4fff7520c20cb1ed8366caffc30e1aeb210', message: 'Reset master branch', gitTags: '', committerDate: 2018-11-01T13:39:50.000Z }, { commit: { long: '927d471ac2f3166cc15dbb59be9af9063742785f', short: '927d471' }, tree: { long: '4b825dc642cb6eb9a060e54bf8d69288fbee4904', short: '4b825dc' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T13:36:28.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T13:36:28.000Z }, subject: 'Cleanup test', body: '', hash: '927d471ac2f3166cc15dbb59be9af9063742785f', message: 'Cleanup test', gitTags: '', committerDate: 2018-11-01T13:36:28.000Z }, { commit: { long: '468a8705685c588eaf6f9fae577a087e57e8b136', short: '468a870' }, tree: { long: '8fc6b912af09f13e4a1675abffce8104442f7a24', short: '8fc6b91' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T13:01:48.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T13:01:48.000Z }, subject: 'Merge branch \'master\' into semantic-release-fix', body: '', hash: '468a8705685c588eaf6f9fae577a087e57e8b136', message: 'Merge branch \'master\' into semantic-release-fix', gitTags: '', committerDate: 2018-11-01T13:01:48.000Z }, { commit: { long: 'cd924da7f9973ec085a15b799666872889b1fc08', short: 'cd924da' }, tree: { long: '8fc6b912af09f13e4a1675abffce8104442f7a24', short: '8fc6b91' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T12:42:43.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T12:42:43.000Z }, subject: 'feat(Add-Object-Dialog): Fix add object dialog id issue', body: '', hash: 'cd924da7f9973ec085a15b799666872889b1fc08', message: 'feat(Add-Object-Dialog): Fix add object dialog id issue', gitTags: '(origin/semantic-release-fix)', committerDate: 2018-11-01T12:42:43.000Z }, { commit: { long: 'e499ba57ad6fe05926d85feeee021d0b1f1b659a', short: 'e499ba5' }, tree: { long: '8d994055591659ea02fcec25dc02fa6c04e07ef1', short: '8d99405' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T12:29:07.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T12:29:07.000Z }, subject: 'feat(Package Json): Merge with semantic-release-fix', body: '', hash: 'e499ba57ad6fe05926d85feeee021d0b1f1b659a', message: 'feat(Package Json): Merge with semantic-release-fix', gitTags: '', committerDate: 2018-11-01T12:29:07.000Z }, { commit: { long: '62464e402c98e309e7d948222da819617875e113', short: '62464e4' }, tree: { long: '433c24648daaa9048771b36ac3f7da4d02cd4f44', short: '433c246' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T12:03:02.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T12:03:02.000Z }, subject: 'feat(Period-Formatter Service): Fix Object Id & Tsconfig issues', body: '', hash: '62464e402c98e309e7d948222da819617875e113', message: 'feat(Period-Formatter Service): Fix Object Id & Tsconfig issues', gitTags: '', committerDate: 2018-11-01T12:03:02.000Z }, { commit: { long: '6386c5d46bf6719e2a691e9ac3e9655cbdc547c9', short: '6386c5d' }, tree: { long: '13a1e53ab982abdec06e2a3aea89ddadb5cadb14', short: '13a1e53' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T08:23:09.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T08:23:09.000Z }, subject: 'feat(Period Formatter Service): Fix tests failing', body: '', hash: '6386c5d46bf6719e2a691e9ac3e9655cbdc547c9', message: 'feat(Period Formatter Service): Fix tests failing', gitTags: '', committerDate: 2018-11-01T08:23:09.000Z }, { commit: { long: '560a89fa9617a108118d619f8df9744307eaea6e', short: '560a89f' }, tree: { long: 'f01e0b671f4a720db6f5613b3e85248a44a3c944', short: 'f01e0b6' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T08:09:47.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-11-01T08:09:47.000Z }, subject: 'build(Period Formatter): Remove import of common web infrastructure in attempt to fix the semantic-r', body: '', hash: '560a89fa9617a108118d619f8df9744307eaea6e', message: 'build(Period Formatter): Remove import of common web infrastructure in attempt to fix the semantic-r', gitTags: '', committerDate: 2018-11-01T08:09:47.000Z }, { commit: { long: 'd4d5c565f0b95a56d8cf6a0803bcd31058c7aa98', short: 'd4d5c56' }, tree: { long: 'f90628ccbeca008c1d4b369f6545c6fac50b2546', short: 'f90628c' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T17:26:59.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T17:26:59.000Z }, subject: 'feat(Package.Json): Add repository details', body: '', hash: 'd4d5c565f0b95a56d8cf6a0803bcd31058c7aa98', message: 'feat(Package.Json): Add repository details', gitTags: '', committerDate: 2018-10-31T17:26:59.000Z }, { commit: { long: 'f335e1186ad763b213d6d29400c9d1cc652d2712', short: 'f335e11' }, tree: { long: 'eee831d82c4f01f11f42aca164f6f2165ac9e2a7', short: 'eee831d' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T16:36:18.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T16:36:18.000Z }, subject: 'feat(Period Formatter Service): Fix period formatter service', body: '', hash: 'f335e1186ad763b213d6d29400c9d1cc652d2712', message: 'feat(Period Formatter Service): Fix period formatter service', gitTags: '', committerDate: 2018-10-31T16:36:18.000Z }, { commit: { long: '38e6ac178ad7e8a59754c088d024f19e9782ab01', short: '38e6ac1' }, tree: { long: '392b17d1c9bcdb877f537183b095d34de7315a1a', short: '392b17d' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T16:06:17.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T16:06:17.000Z }, subject: 'build: Fix failing build due to string format', body: '', hash: '38e6ac178ad7e8a59754c088d024f19e9782ab01', message: 'build: Fix failing build due to string format', gitTags: '', committerDate: 2018-10-31T16:06:17.000Z }, { commit: { long: '49b04624a76062c9b319d927747b19109120fcbe', short: '49b0462' }, tree: { long: 'da3b79b787457d29033cd2f86d8233214f5218d4', short: 'da3b79b' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T13:01:28.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T13:01:28.000Z }, subject: 'build: Fix build failing', body: '', hash: '49b04624a76062c9b319d927747b19109120fcbe', message: 'build: Fix build failing', gitTags: '', committerDate: 2018-10-31T13:01:28.000Z }, { commit: { long: '4e7631927278bd9be5916fa0d9a770fd85e5ebdc', short: '4e76319' }, tree: { long: '7b1d262374d5c2278231d320daf179903e65cad2', short: '7b1d262' }, author: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T12:10:59.000Z }, committer: { name: 'Ovidiu', email: 'ovidiu.ban@webfactory-world.de', date: 2018-10-31T12:10:59.000Z }, subject: 'fix(Add-Object-Dialog): Fix object id validation', body: '', hash: '4e7631927278bd9be5916fa0d9a770fd85e5ebdc', message: 'fix(Add-Object-Dialog): Fix object id validation', gitTags: '', committerDate: 2018-10-31T12:10:59.000Z } ]
2018-11-01T16:39:28.9960952Z [17:39:28] [semantic-release] » i  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: chore(workspace.xml): Remove workspace.xml
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: chore(Package.json): Update ko-am charts package
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: Reset master branch
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: Cleanup test
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: Merge branch 'master' into semantic-release-fix
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: feat(Add-Object-Dialog): Fix add object dialog id issue
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is minor
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: feat(Package Json): Merge with semantic-release-fix
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is minor
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: feat(Period-Formatter Service): Fix Object Id & Tsconfig issues
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is minor
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: feat(Period Formatter Service): Fix tests failing
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is minor
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: build(Period Formatter): Remove import of common web infrastructure in attempt to fix the semantic-r
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: feat(Package.Json): Add repository details
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is minor
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: feat(Period Formatter Service): Fix period formatter service
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is minor
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: build: Fix failing build due to string format
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: build: Fix build failing
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The commit should not trigger a release
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: fix(Add-Object-Dialog): Fix object id validation
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer Analyzing with default rules
2018-11-01T16:39:29.0117208Z 2018-11-01T16:39:29.010Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is patch
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] [@semantic-release/commit-analyzer] » i  Analysis of 15 commits complete: minor release
2018-11-01T16:39:29.0117208Z [17:39:29] [semantic-release] » √  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
2018-11-01T16:39:29.0742201Z [17:39:29] [semantic-release] » i  The next release version is 1.45.0
2018-11-01T16:39:29.9804957Z [17:39:29] [semantic-release] » i  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2018-11-01T16:39:29.9968798Z 2018-11-01T16:39:29.088Z semantic-release:release-notes-generator version: '1.45.0'
2018-11-01T16:39:29.9968798Z 2018-11-01T16:39:29.088Z semantic-release:release-notes-generator host: 'tfs2013'
2018-11-01T16:39:29.9968798Z 2018-11-01T16:39:29.088Z semantic-release:release-notes-generator owner: 'tfs'
2018-11-01T16:39:29.9968798Z 2018-11-01T16:39:29.088Z semantic-release:release-notes-generator repository: 'DWH/WEBfactory.BACnet/_git/bacnet-web-controls'
2018-11-01T16:39:29.9968798Z 2018-11-01T16:39:29.088Z semantic-release:release-notes-generator previousTag: 'v1.44.1'
2018-11-01T16:39:29.9968798Z 2018-11-01T16:39:29.088Z semantic-release:release-notes-generator currentTag: 'v1.45.0'
2018-11-01T16:39:29.9968798Z [17:39:29] [semantic-release] » √  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2018-11-01T16:39:29.9968798Z [17:39:29] [semantic-release] » i  Start step "prepare" of plugin "@semantic-release/changelog"
2018-11-01T16:39:29.9968798Z [17:39:29] [semantic-release] [@semantic-release/changelog] » i  Update C:\Agents\TFS2013-1\_work\87\s\CHANGELOG.md
2018-11-01T16:39:29.9968798Z [17:39:29] [semantic-release] » √  Completed step "prepare" of plugin "@semantic-release/changelog"
2018-11-01T16:39:29.9968798Z [17:39:29] [semantic-release] » i  Start step "prepare" of plugin "@semantic-release/git"
2018-11-01T16:39:29.9968798Z 2018-11-01T16:39:29.479Z semantic-release:git globed assets: [ 'package.json', 'dist/bacnet-web-controls.module.js', 'dist/bacnet-web-controls.module.js.map', 'dist/bacnet.app.js', 'dist/bacnet.app.js.map', 'dist/components', 'dist/dialogs', 'dist/extensions', 'dist/index.js', 'dist/index.js.map', 'dist/locale', 'dist/services', 'dist/types', 'dist/view-models', 'dist/components/any-value-picker', 'dist/components/bacnet-object.component.js.map', 'dist/components/bacnet-object.component.js', 'dist/components/bacnet-object.component.xspec.js', 'dist/components/bacnet-object.component.xspec.js.map', 'dist/components/bacnet.component.js', 'dist/components/bacnet.component.js.map', 'dist/components/bacnet.component.xspec.js', 'dist/components/bacnet.component.xspec.js.map', 'dist/components/components.module.js', 'dist/components/components.module.js.map', 'dist/components/date-picker', 'dist/components/date-range-picker', 'dist/components/device', 'dist/components/devices.json', 'dist/components/interfaces', 'dist/components/loop-control', 'dist/components/object-browser', 'dist/components/object-component-names.js', 'dist/components/object-component-names.js.map', 'dist/components/object-loader', 'dist/components/property-lister.component.js', 'dist/components/property-lister.component.js.map', 'dist/components/property-lister.component.xspec.js', 'dist/components/property-lister.component.xspec.js.map', 'dist/components/property-selector', 'dist/components/property-viewer', 'dist/components/scheduler', 'dist/components/select-device-object', 'dist/components/shared', 'dist/components/time-picker', 'dist/components/time-range-picker', 'dist/components/toolbar', 'dist/components/trend', 'dist/dialogs/add', 'dist/dialogs/delete-confirmation', 'dist/dialogs/dialogs.module.js', 'dist/dialogs/dialogs.module.js.map', 'dist/dialogs/event-algorithm-reference', 'dist/dialogs/interfaces', 'dist/dialogs/object-property-editor', 'dist/dialogs/object-property-selector', 'dist/dialogs/object-selector', 'dist/dialogs/scheduler-exception-schedule', 'dist/dialogs/scheduler-exception-schedule-entry', 'dist/dialogs/scheduler-weekly-schedule-operations', 'dist/extensions/extensions.module.js', 'dist/extensions/extensions.module.js.map', 'dist/extensions/flags-enum-to-array.extender.js', 'dist/extensions/flags-enum-to-array.extender.js.map', 'dist/extensions/flags-enum-to-array.extender.spec.js', 'dist/extensions/flags-enum-to-array.extender.spec.js.map', 'dist/locale/de.json', 'dist/locale/en.json', 'dist/locale/json.module.js', 'dist/locale/json.module.js.map', 'dist/services/api', 'dist/services/bacnet.service.js', 'dist/services/bacnet.service.js.map', 'dist/services/bacnet.service.spec.js', 'dist/services/bacnet.service.spec.js.map', 'dist/services/component-communication.service.js', 'dist/services/component-communication.service.js.map', 'dist/services/component-communication.service.spec.js', 'dist/services/component-communication.service.spec.js.map', 'dist/services/component-filter.service.js', 'dist/services/component-filter.service.js.map', 'dist/services/discovery-info-merge.service.js', 'dist/services/discovery-info-merge.service.js.map', 'dist/services/discovery-info-merge.service.spec.js', 'dist/services/discovery-info-merge.service.spec.js.map', 'dist/services/icon-set-provider.service.js', 'dist/services/icon-set-provider.service.js.map', 'dist/services/icon-set-provider.service.spec.js', 'dist/services/icon-set-provider.service.spec.js.map', 'dist/services/key-generator.service.js', 'dist/services/key-generator.service.js.map', 'dist/services/key-generator.service.spec.js', 'dist/services/key-generator.service.spec.js.map', 'dist/services/messages', 'dist/services/period-formatter.service.js', 'dist/services/period-formatter.service.js.map', 'dist/services/period-formatter.service.spec.js', 'dist/services/period-formatter.service.spec.js.map', 'dist/services/property-measurement-subscription.js', 'dist/services/property-measurement-subscription.js.map', ... 722 more items ]
2018-11-01T16:39:29.9968798Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2018-11-01T16:39:29.9968798Z [17:39:29] [semantic-release] » ×  Failed step "prepare" of plugin "@semantic-release/git"
2018-11-01T16:39:29.9968798Z [17:39:29] [semantic-release] » ×  An error occurred while running semantic-release: { Error: spawn ENAMETOOLONG
2018-11-01T16:39:29.9968798Z     at _errnoException (util.js:1022:11)
2018-11-01T16:39:29.9968798Z     at ChildProcess.spawn (internal/child_process.js:323:11)
2018-11-01T16:39:29.9968798Z     at Object.exports.spawn (child_process.js:502:9)
2018-11-01T16:39:29.9968798Z     at Module.module.exports (C:\Agents\TFS2013-1\_work\87\s\node_modules\execa\index.js:205:26)
2018-11-01T16:39:29.9968798Z     at Function.module.exports.stdout.args [as stdout] (C:\Agents\TFS2013-1\_work\87\s\node_modules\execa\index.js:319:45)
2018-11-01T16:39:30.0117349Z     at filterModifiedFiles (C:\Agents\TFS2013-1\_work\87\s\node_modules\@semantic-release\git\lib\git.js:13:23)
2018-11-01T16:39:30.0117349Z     at module.exports (C:\Agents\TFS2013-1\_work\87\s\node_modules\@semantic-release\git\lib\prepare.js:34:33)
2018-11-01T16:39:30.0117349Z     at <anonymous>
2018-11-01T16:39:30.0117349Z     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-11-01T16:39:30.0117349Z   code: 'ENAMETOOLONG',
2018-11-01T16:39:30.0117349Z   errno: 'ENAMETOOLONG',
2018-11-01T16:39:30.0117349Z   syscall: 'spawn',
2018-11-01T16:39:30.0117349Z   pluginName: '@semantic-release/git' }
2018-11-01T16:39:30.0117349Z { Error: spawn ENAMETOOLONG
2018-11-01T16:39:30.0117349Z     at _errnoException (util.js:1022:11)
2018-11-01T16:39:30.0117349Z     at ChildProcess.spawn (internal/child_process.js:323:11)
2018-11-01T16:39:30.0117349Z     at Object.exports.spawn (child_process.js:502:9)
2018-11-01T16:39:30.0117349Z     at Module.module.exports (C:\Agents\TFS2013-1\_work\87\s\node_modules\execa\index.js:205:26)
2018-11-01T16:39:30.0117349Z     at Function.module.exports.stdout.args [as stdout] (C:\Agents\TFS2013-1\_work\87\s\node_modules\execa\index.js:319:45)
2018-11-01T16:39:30.0117349Z     at filterModifiedFiles (C:\Agents\TFS2013-1\_work\87\s\node_modules\@semantic-release\git\lib\git.js:13:23)
2018-11-01T16:39:30.0117349Z     at module.exports (C:\Agents\TFS2013-1\_work\87\s\node_modules\@semantic-release\git\lib\prepare.js:34:33)
2018-11-01T16:39:30.0117349Z     at <anonymous>
2018-11-01T16:39:30.0117349Z     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-11-01T16:39:30.0117349Z   code: [32m'ENAMETOOLONG'[39m,
2018-11-01T16:39:30.0117349Z   errno: [32m'ENAMETOOLONG'[39m,
2018-11-01T16:39:30.0117349Z   syscall: [32m'spawn'[39m,
2018-11-01T16:39:30.0117349Z   pluginName: [32m'@semantic-release/git'[39m }error Command failed with exit code 1.
2018-11-01T16:39:30.0117349Z ##[error]Error: C:\Agents\TFS2013-1\_work\_tool\yarn\1.12.1\x64\yarn-v1.12.1\bin\yarn.cmd failed with return code: 1
2018-11-01T16:39:30.0273614Z ##[section]Finishing: Yarn semantic-release --debug

**Comment by pvdlg** [comment]
So it seems that around 800 files are resolved from the glob. See the line `2018-11-01T16:39:29.9968798Z 2018-11-01T16:39:29.479Z semantic-release:git globed assets:`.

Are you sure your configuration for `assets` is `['CHANGELOG.md']`?
It seems you also configured the `dist` directory which contains all those files. It seems you have a bunch of `.js` files there and each one has an associated a `.js.map` file.

Is it intentional? Do you really want to commit all those files in the `dist` directory? Shouldn't you create a bundle and push only that?

**Comment by pvdlg** [comment]
I tested again and I don't see how the files in `dist` could be resolved. You must have that configured somewhere.
Maybe if you provide a link to your repo I can look at it.

**Comment by pvdlg** [comment]
I just released `semantic-release@15.10.7` with additional debug logs regarding plugin config.
Can you update to that version, run it again with the `--debug` option and paste the logs here?

**Comment by OvidiuBan** [comment]
Greetings! Sorry for answering but I've been away. The config file seemed to have some issues & and now it seems to be working properly.

Thank you for all the answers!

**Comment by ChristianUlbrich** [comment]
This is still a problem. It will happen, when `execa()` (and thus down the chain `spawn()`) tries to call a program with arguments passed that are _too long_ for the current environment. This is depending on your OS / shell. On Windows it seems to [be quite small](https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string), i.e. _just_ roughly 8k. This is pretty easy to hit with a decent amount of changes.

The error message is mis-leading, it it not about the length of the filename, but about the maximum length of passed arguments as well.

All occurrences in the code, where basically unrestricted amount of data is passed to `git` are affected (e.g. [gitCommit](https://github.com/semantic-release/git/blob/09e00f98205e81e17ad9ec056a1efe20b42efb2a/lib/git.js#L38) adding all changes in the commit messages). Passing unrestricted amounts of data, via command line arguments won't work reliably.

For `git commit` a _reliably_ workaround is to read the commit message from a temporarily created file. I am working on a PR right now; however this will very likely affect the git note handling as well.

**Comment by pcnate** [comment]
I ran into this issue when trying to add semantic-release to an existing project. It generated a changelog file of over 2k lines which fails on ubuntu. Is there any way to reduce this or truncate the commit message in the event it does end up too long?
